# -*- coding: utf-8 -*-
"""00-TensorFlow-Basic-Syntax.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VMMgY_pjb8bPGwdG72kewZFRX7Y31jqq

# TensorFlow Basics
"""

import tensorflow as tf

# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

"""## Tensors"""

hello = tf.constant('Hello')

type(hello)

world = tf.constant('World')

result = hello + world

result

type(result)

with tf.Session() as sess:
    result = sess.run(hello+world)

result

"""** Computations **"""

tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

type(tensor_1)

tensor_1 + tensor_2

sess

sess.close()

"""## Operations"""

const = tf.constant(10)

fill_mat = tf.fill((4,4),10)

myzeros = tf.zeros((4,4))

myones = tf.ones((4,4))

myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

"""## Interactive Session

Useful for Notebook Sessions
"""

# Only run this cell once!
sess = tf.InteractiveSession()

for op in my_ops:
    print(op.eval())
    print('\n')

"""## Matrix Multiplication"""

a = tf.constant([ [1,2],
                  [3,4] ])

a.get_shape()

b = tf.constant([[10],[100]])

b.get_shape()

result = tf.matmul(a,b)

result.eval()

