# -*- coding: utf-8 -*-
"""01-TensorFlow-Graphs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1judI2F4Hb9VKwwlzeqRLIrvX85DrQi8x

# TensorFlow Graphs
"""

import tensorflow as tf

"""### Simple Example"""

n1 = tf.constant(1)
n2 = tf.constant(2)

n3 = n1 + n2

# Using with auto-closes the session
with tf.Session() as sess:
    result = sess.run(n3)
print(result)

"""___
When you start TF, a default Graph is created, you can create additional graphs easily:
"""

print(tf.get_default_graph())

g = tf.Graph()

print(g)

"""Setting a graph as the default:"""

graph_one = tf.get_default_graph()
graph_two = tf.Graph()

graph_one is tf.get_default_graph()

graph_two is tf.get_default_graph()

with graph_two.as_default():
    print(graph_two is tf.get_default_graph())

graph_two is tf.get_default_graph()

