# -*- coding: utf-8 -*-
"""02-Variables-and-Placeholders.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16nfGcGhU5tTT_IxDM0oiSjuQVBT4ugxq

# Variables and Placeholders
"""

import tensorflow as tf

sess = tf.InteractiveSession()

"""## Variables"""

my_tensor = tf.random_uniform((4,4),0,1)

my_var = tf.Variable(initial_value=my_tensor)

print(my_var)

"""#### Note! You must initialize all global variables!"""

# This line is really important, it is easy to forget!
init = tf.global_variables_initializer()

init.run()

my_var.eval()

sess.run(my_var)

"""## Placeholders"""

ph = tf.placeholder(tf.float64)

ph = tf.placeholder(tf.int32)

# For shape its common to use (None,# of Features) 
# because None can be filled by number of samples in data
ph = tf.placeholder(tf.float32,shape=(None,5))

"""Coming up next is where we'll put this all together!"""